apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-tester
  template:
    metadata:
      labels:
        app: selenium-tester
    spec:
      containers:
      - name: selenium-tester
        image: hasanaliyev555/selenium-test-runner
        env:
        - name: SELENIUM_HUB
          value: "http://selenium-hub:4444/wd/hub"
