apiVersion: v1
kind: Pod
metadata:
  name: selenium-tester
  labels:
    app: selenium-tester
spec:
  containers:
  - name: selenium-tester
    image: hasanaliyev555/selenium-test-runner
    env:
    - name: SELENIUM_HUB
      value: "http://selenium-hub:4444/wd/hub"
